name: flut_run
description: Flutter Application designed to bring the running community together and serve as a useful team tool.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "^0.4.2"
  firebase_auth: ^0.5.11
  #firebase_auth: 0.1.1
  #firebase_database: 0.0.12
  #firebase_storage: 0.0.5


  # The following adds the Cupertino Icons font to your application.
  # Use with the Cupertino Icons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
      - assets/icons/ai_brain.png
      - assets/icons/barbell.png
      - assets/images/abstract_runner.png
      - assets/images/rainbow_runner.png
      - assets/images/run_background.jpg
      - assets/images/run_community.jpg
      - assets/images/bears.png
      - assets/images/lutes.png
      - assets/images/panther.png
      - assets/images/noProfileIcon.png
      - assets/images/runnerIcon.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
  fonts:
      - family: Aileron
        fonts:
        - asset: assets/fonts/Aileron/Aileron-SemiBold.ttf